### ISSUE TITLE
Authentication Module

### ISSUE THREAD

**Issue by hnordt** [smalldots/smalldots#1]
I would like to propose a decoupled authentication module for Redux.

The idea is that this module should be generic, you should be able to use it with oAuth, Passport, Auth0, your custom backend, etc.

In the future we'll also build an authorization module.

The first step is create a common API, here is the first draft:

``` js
function login() {}

function logout() {}

function signup() {}

function resetPassword() {}

function changePassword() {}
```

**Comment by globsecure** [comment]
i believe that the proposal is meeting with the agility of daily work. +1
