### ISSUE TITLE
Long page-list Paginator

### ISSUE THREAD

**Issue by femesq** [smalldots/smalldots#10]
First of all, very nice project...

I was wondering how (and if) I could use the `Pagination` component to achieve the result I have with very long page-lists:

When I have 1st page selected, I get:
![image](https://cloud.githubusercontent.com/assets/1899668/18335397/5e5566a6-7555-11e6-96b5-48cb350433f9.png)

When I have one "middle" page selected, I get this:
![image](https://cloud.githubusercontent.com/assets/1899668/18335426/8af4d30e-7555-11e6-8768-80571315631a.png)

I can use `range(1,3)` to render the 3-first and `range(numberOfPages -3, numberOfPages )` to the 3-last pages I always show... But that would make me repeat the rendering code 3-times...

For the "longer-step" intervals, I'm no sure how to deal with it...

Maybe I should `extends` (sub-class) from your `Component`, re-writing only the `getPageRange` function??
In the result list, I could return non-integer (`null`) for non-pages `...` rendering....

**Comment by hnordt** [comment]
You can do it using `lodash/range`:

``` js
import lodashRange from 'lodash/range'
import uniq from 'lodash/uniq'

function range(start, end, step) {
  // in lodash's range end is not included, so we need to add 1
  return lodashRange(start, end + 1, step)
}

const longPageList = uniq([
  ...[1, 2, 3],
  ...range(10, currentPage - 10, 10),
  ...range(currentPage - 10, currentPage + 10),
  ...range(currentPage + 10, numberOfPages - 10, 10),
  ...range(numberOfPages - 2, numberOfPages)
])
```
