### ISSUE TITLE
[Storage] Support driver with async API

### ISSUE THREAD

**Issue by zetachang** [smalldots/smalldots#11]
I am trying to implement an AsyncStorage driver in React Native which only provides async `getItem` & `setItem` (see https://facebook.github.io/react-native/releases/next/docs/asyncstorage.html#getitem)

Any plan on making the driver interface more generic, given that the current sync driver could be implemented synchronously.

**Comment by hnordt** [comment]
You mean you want Storage to support async drivers like RN AsyncStorage?

**Comment by zetachang** [comment]
Yap.

Héliton Nordt notifications@github.com 於 2016年9月10日週六 下午3:41 寫道：

**Comment by hnordt** [comment]
Yup, that's a good feature to have because I want to support both RN and Mozilla's localForage.

I'll implement async support tomorrow.

**Comment by zetachang** [comment]
Awesome! 

By the way, it is quite fun to see all these components abstraction encapsulate behavior rather just UI hierarchy.

**Comment by hnordt** [comment]
Yeah, actually for the first versions of Smalldots I released UI, but I found it impractical because every project has specific UI concerns, so it's best to provide behavior instead UI.

**Comment by hnordt** [comment]
@zetachang I have released a experimental version of `AsyncStorage`, you can import it from`smalldots/lib/experimental/AsyncStorage`.

It works like `Storage`, but `getItem` and `setItem` should return promises.

If you want to use with RN you probably will need to write a special component:

``` jsx
import React from 'react'
import Storage from 'smalldots/lib/experimental/AsyncStorage'

export default function RNStorage(props) {
  return (
    <Storage
      {...props}
      driver={{
        getItem: async key => await AsyncStorage.getItem(key),
        setItem: async (key, value) => await AsyncStorage.setItem(key, value)
      }}
    />
  )
}

RNStorage.propTypes = { subscribe: Storage.propTypes.subscribe }
```

**Comment by zetachang** [comment]
The promise callback will try to `setState` even when the component is unmounted. Looks like an issue solved by this [react-safe-promise](https://github.com/reactnativecn/react-safe-promise).

**Comment by hnordt** [comment]
@zetachang thank you, I'll fix next monday.

**Comment by hnordt** [comment]
@zetachang can you test it again please? Fixed in `v0.26.7` with https://github.com/smalldots/smalldots/commit/66919b3a5ecdd0a009876e94d9b6c867e62d3680.

**Comment by zetachang** [comment]
Warning still raised by `setState` at https://github.com/smalldots/smalldots/blob/master/src/experimental/AsyncStorage.js#L26, maybe do some `this.willUnmount` check there?

**Comment by hnordt** [comment]
@zetachang yup, fixed with https://github.com/smalldots/smalldots/commit/b2fcba15f2e8d90951108312ba38fabc2689da49. Thanks!

Can you try again?

**Comment by hnordt** [comment]
@zetachang can you do another test? Please let me know if it works:

``` jsx
import React from 'react'
import Storage from 'smalldots/lib/experimental/AsyncStorage'

export default function RNStorage(props) {
  return <Storage {...props} driver={AsyncStorage} />
}

RNStorage.propTypes = {
  initialValues: Storage.propTypes.initialValues,
  subscribe: Storage.propTypes.subscribe
}

```

**Comment by zetachang** [comment]
Works fine now, thanks!
