### ISSUE TITLE
isDirty for a single field

### ISSUE THREAD

**Issue by fson** [smalldots/smalldots#17]
I wanted to make a form that validates each field only after it's been edited (`onChage` or `onBlur` has fired), or alternatively validates all the fields after the user has tried to submit the form.

Can this be done using the `Form` component? The `isDirty` field is currently only available for the whole form, not single fields.

**Comment by hnordt** [comment]
I'm on a vacation now, but I'll try to implement this option today.

Just to confirm, isDirty(fieldName) is what you need?

**Comment by fson** [comment]
I think so, but I'm not sure, if the dirty check based on value works for my use case: I would also want to track if the user edited the value. After writing something to the input and then clearing it again, the input should still be "dirty", even though it would match the initial value.

**Comment by hnordt** [comment]
I'll implement additional state to keep track of touched values, your use case is more common than my first implementation just comparing values.

**Comment by hnordt** [comment]
@fson I have implemented the suggested feature. I hope it helps.
