### ISSUE TITLE
v0.33.0

### ISSUE THREAD

**Issue by hnordt** [smalldots/smalldots#29]
Moved to #30

**Comment by andersonfelix** [comment]
Why will you remove Bulma support?

**Comment by hnordt** [comment]
@andersonfelix because the purpose of Smalldots is to be UI agnostic, it'll provide only behavior instead UI.

Also I added Bulma support as an experiment, but for some projects I'm using Bootstrap, or even no CSS framework. So I won't have time to support Bulma components.

I want to keep on Smalldots only modules which I use on all my projects, so I have time to test, improve and fix bugs.

**Comment by andersonfelix** [comment]
Alright! Make sense ;)
