### ISSUE TITLE
Fetch componentWillReceiveProps

### ISSUE THREAD

**Issue by schuchowsky** [smalldots/smalldots#32]
Currently, on Fetch's `componentWillReceiveProps`, it does the following:

```javascript
componentWillReceiveProps(nextProps) {
    if (!this.props.lazy && !isEqual(this.props, nextProps)) {
      this.fetch()
    }
  }
```

I have a use case that depending on the parent's props, the Fetch's `lazy` prop should change between `true` and `false`.
In that case, if the initial prop was `true`, it will never fetch again.

My solution was the following:

```javascript
componentWillReceiveProps(nextProps) {
    if (!nextProps.lazy) {
      this.fetch()
    }
  }
```
What do you think?

**Comment by hnordt** [comment]
Here's my suggestion:

```jsx
componentDidMount() {
  if (this.props.lazy) {
    return
  }
  this.fetch(this.props.body)
}

componentWillReceiveProps(nextProps) {
  if (nextProps.lazy) {
    return
  }
  if (isEqual(nextProps, this.props)) {
    return
  }
  this.fetch(nextProps.body)
}
```

Do you think it'll resolve your problem?

**Comment by schuchowsky** [comment]
@hnordt Yes, that works perfectly.

**Comment by hnordt** [comment]
@schuchowsky can you create a pull request please?
