### ISSUE TITLE
Support `withCredentials` axios property

### ISSUE THREAD

**Issue by jfsiii** [smalldots/smalldots#35]
This is crucial for CORS requests.

**Comment by hnordt** [comment]
Hey @jfsiii, thank you for trying Smalldots.

Fetch can be fully customized, please read https://github.com/smalldots/smalldots/wiki/Customizing-Fetch

**Comment by jfsiii** [comment]
@hnordt I read that, but am not clear on how I'd get the `withCredentials` param through. From what I saw in [the source](https://github.com/smalldots/smalldots/blob/v0.33.0/src/FetchService.js#L83-L88) you can only use the `method`, `url`, `params`, `headers` and `data` params for `axios`.

**Comment by hnordt** [comment]
Yeah, you are right @jfsiii.

Do you want to create a pull request?

**Comment by hnordt** [comment]
Merged, sorry the huge delay to approve.
