### ISSUE TITLE
mouseover mouseout with toggler

### ISSUE THREAD

**Issue by zebapy** [smalldots/smalldots#38]
Hi I'm wondering about appropriate use for `Toggler` with `onMouseOver`/`onMouseOut`. 

I'm getting content that flashes in and out when I use it this way:

https://www.webpackbin.com/bins/-Kenr9lKWS5XvNaf31dc

Is there a way to prevent the `<Icon/>` from flashing? does the Icon need `shouldComponentUpdate`?

**Comment by hnordt** [comment]
Hey!

The problem is that when the `<Icon />` disappears the parent div triggers additional events, causing the blink effect.

In this case, you can use the `visibility` CSS property to fix the problem. https://www.webpackbin.com/bins/-Keo-vYZjUkJfWQt6R3O

Does it helps?

**Comment by hnordt** [comment]
@zebapy a better fix would be changing `onMouseOver` to `onMouseEnter` and `onMouseOut` to `onMouseLeave`. https://www.webpackbin.com/bins/-Keo3eNPOcUMiw-z0gc-

The `onMouseEnter` event does not trigger when the mouse pointer leaves any child elements.

Same for `onMouseLeave` vs `onMouseOut`. https://www.w3schools.com/jquery/tryit.asp?filename=tryjquery_event_mouseleave_mouseout

**Comment by zebapy** [comment]
@hnordt thanks so much for the help on this. These both look like great solutions. Nice lib btw--very helpful.

**Comment by hnordt** [comment]
You are welcome @zebapy 👍🏻
