### ISSUE TITLE
componentWillReceiveProps calling dispatch with old props

### ISSUE THREAD

**Issue by tutturen** [smalldots/smalldots#39]
I have a use case where I am using Fetch, and I am changing the url parameter.
This calls the internal `componentWillReceiveProps` method in Fetch, which again calls `this.dispatch(nextProps.body)`.

My problem is that the dispatch is called again with the *previous* url, not the url i updated to. I suspect this is because `dispatch` is not passed the new props, and is hence using the old ones.

**Comment by hnordt** [comment]
Thanks for the report. Fixed and released v0.35.1.

**Comment by tutturen** [comment]
Tested, and it works. Thanks a lot!

**Comment by hnordt** [comment]
Awesome. Closing 👍
