### ISSUE TITLE
Exemplo

### ISSUE THREAD

**Issue by fernandofranca** [smalldots/smalldots#40]
Vi a gravação video da BrazilJS e ficou um pouco dificil acompanhar os exemplos.
Acho que perdi alguma coisa e meu teste não funcionou. 
Só consigo fazer o get, mas o valor não é atualizado no render.
Minha intenção aqui é usar a store só para armazenar temporariamente.

```
import React from 'react';
import {SyncStorage} from 'smalldots'

const defaultValue = {
  number: 222
}

const MemStore = props => (
  <SyncStorage
    {...props}
    driver={{
      getItem: key => defaultValue[key],
      setItem: (key, value) => {
        defaultValue[key] = value
        return value
      }
    }}
  />
)

export default class App extends React.Component {
  render(){
    return (
      <MemStore subscribeTo="number">
        {({setItem, getItem, number}) => {
          return (
            <div>
              <p>my number: {number}</p>
              <p>getItem: {getItem('number')}</p>
              <button onClick={() => setItem('number', 1000)}>setItem</button>
            </div>
          )
        }}
      </MemStore>
    )
  }
} 
```

**Comment by hnordt** [comment]
Desculpe o atraso de alguns meses na resposta, hehe.

Vc nao estava fazendo nada errado, uma otimização boba que tentei fazer quebrou a lib. Enviei uma correção.

Nao recomendo mais usar o `SyncStorage`, ele funciona, porem vc vai ter problemas se algum componente pai retornar false no `shouldComponentUpdate`.

Criei uma nova lib pra gerenciar estado que resolve este problema mas exige React 16.3+: https://github.com/smalldots/create-container
