### ISSUE TITLE
Object.freeze

### ISSUE THREAD

**Issue by hnordt** [smalldots/smalldots#5]
State/props passed to `children()` shouldn't be mutated.

``` js
  render() {
    return this.props.children({ data: this.state.data, error: this.state.error })
  }
```

In this example `data` and `error` shouldn't mutated by the consumer.

To prevent mutation, I think that we can do something like this:

``` js
  render() {
    const frozenState = deepFreeze({ ...this.state })
    return this.props.children(frozenState)
  }
```

**Comment by hnordt** [comment]
@dan_abramov I would love to hear your opinion on this.

**Comment by hnordt** [comment]
@gaeron I would love to hear your opinion on this.

**Comment by hnordt** [comment]
@gaearon I would love to hear your opinion on this.

**Comment by hnordt** [comment]
I won't implement it for now.

**Comment by gaearon** [comment]
Freezing is also somewhat slow, I'd only recommend it in development.

**Comment by hnordt** [comment]
Thank you @gaearon
