### ISSUE TITLE
Fetch component implicit behavior

### ISSUE THREAD

**Issue by thinkimlazy** [smalldots/smalldots#6]
```
  componentDidMount() {
    if (!this.props.lazy) {
      this.fetch()
    }
  }
```

If user didn't defined `lazy` prop then it's gonna be `undefined`, but `!undefined` converts to `true`. 
So `Fetch` is not lazy by default.

**Comment by hnordt** [comment]
Thank you for getting in touch @thinkimlazy!

`Fetch` is not lazy by default, the reason is that in my production code I have used more `GET` than `POST`, `PUT` or `DELETE`. That's the reason that the default `method` is `get`.

An example:

``` js
const UserListContainer = () => (
  <Fetch url="/users">
    {({ data }) => data && <UserList users={data} />}
  </Fetch>
)
```
