### ISSUE TITLE
<Paginator /> - Is the intent of getPageRange() clear?

### ISSUE THREAD

**Issue by hnordt** [smalldots/smalldots#8]
I don't know if `getRangePage()` is a good name for the method that returns the page range (it accepts an offset).

The current API is `getPageRange(offset)`, if the current page is 10 and you pass an offset 3, it would return `[7, 8, 9, 10, 11, 12, 13]`.

I would like to hear thoughts on this. `getPages()` is an option, but as `Paginator` passes down `page`, I think it would be confusing to have `page` and `getPages()`, in that case `getPageRange()`, is more clear in my opinion.

**Comment by schuchowsky** [comment]
getPages is clear enought to me, refers to a list of pages, which are numbers. getPageList has a nice semantic as well.

Range for me seems like the difference between two elements, or the element "x" and "y" of an array:
![image](https://cloud.githubusercontent.com/assets/13025585/18289032/11e403d8-7454-11e6-99b2-c00a4a2ea55a.png)

**Comment by femesq** [comment]
Since page range is generated from `currentPage`, maybe `getRangeFromCurrent` could be 
most obvious... The `offset` parameters goes up and down, respecting `start` and `end`.

**Comment by hnordt** [comment]
I had a productive talk with @femesq on Slack and we have figured that `getPageRange()` is unnecessary, you can do the same thing easily with lodash's `range()`: https://github.com/smalldots/smalldots/commit/8dce778cf82bf9943874e21e51338dee01404c85
